[project]
name = "ai-assitant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["dspy>=2.6.27", "fastapi[standard]>=0.116.1"]

[dependency-groups]
dev = ["ipykernel>=6.30.0", "mlflow>=3.1.4"]
